### PR TITLE
fix: template-functions now correctly work for name, namespace etc.

### LINKED ISSUE #2138: [Bug] JMESPath conditions for name, namespace or labels don't work
### chainsaw version Version

v0.2.11

### Description

JMESPath conditions for name or namespace are ignored. When a JMESPath condition is used for a label, *all* labels are ignored. In our setup this resulted in strange sporadic failures where totally different resources from other tests were matched.

The problem is that `ResourceRef` assumes that the values for those properties are string and silently removes them as a side-effect when they aren't, removing all labels if any label value isn't a string.

This could be considered an unsupported feature, but because of the strange behaviour and the clear cause I found in the code I think it can be considered a bug.

I already created a fix for which I will submit a pull request.

### Steps to reproduce

1. Run the following test:
  ```
  apiVersion: chainsaw.kyverno.io/v1alpha1
  kind: Test
  metadata:
    name: metadata-template-conditions
  spec:
    steps:
      - try:
          - apply:
              resource:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  labels:
                    color: green
                    type: peugeot
                    top_speed: '130'
                  name: peugeot-206
          - assert:
              resource:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  labels:
                    color: red
                    type: ferrari
                    top_speed:
                      (to_number(@) > `200`): true
                  name:
                    (starts_with(@, 'ferrari-')): true
  ```

### Expected behavior

The test should fail because four conditions don't match, of which two are not even JMESPath conditions.

### Screenshots

_No response_

### Logs

_No response_

### Slack discussion

_No response_

### Troubleshooting

- [X] I have searched other issues in this repository and mine is not recorded.

### PR DESCRIPTION
**Pull request by bertbaron**
…bels

## Explanation

JMESPath conditions for name or namespace are ignored. When a JMESPath condition is used for a label, all labels are ignored. In our setup this resulted in strange sporadic failures where totally different resources from other tests were matched.

## Related issue

Fixes #2138

## Proposed Changes

The current code uses the getters and setters from Unstructured, i.e.:

```
	temp.SetNamespace(obj.GetNamespace())
	temp.SetLabels(obj.GetLabels())
	
	... perform templating on temp
	
	obj.SetNamespace(temp.GetNamespace())
	obj.SetLabels(temp.GetLabels())
```

The problem here is that the `Get...` methods will return empty values if the values are not strings, and by setting them back to `obj` the existing structured values are overwritten.

The fix involves two changes:
1. Instead of using `obj.GetLabels()`, which returns `nil` if any label value is not a string, filter all `string` labels ignoring any other label.
2. Instead of copying the properties back using the setters, use `obj.Object = maps.Merge(obj.Object, merged.UnstructuredContent())` to avoid that structured values will be removed from `obj` simply because they are absent in the templated object.

## Checklist

- [x ] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.
- [ x] This is a bug fix and I have added unit tests that prove my fix is effective.

### CODE REVIEW

File: pkg/engine/templating/resource_ref.go [hunk 1]
```diff
@@ -24,17 +25,27 @@ func ResourceRef(ctx context.Context, c compilers.Compilers, obj *unstructured.U
...
+	if labels, ok, _ := unstructured.NestedFieldNoCopy(obj.UnstructuredContent(), "metadata", "labels"); ok {
+		if labelsMap, ok := labels.(map[string]interface{}); ok {
+			tempLabels := make(map[string]string)
+			for k, v := range labelsMap {
+				if stringValue, ok := v.(string); ok {
+					tempLabels[k] = stringValue
+				}
+			}
+			return tempLabels
+		}
```
Comment (eddycharly) [inline pkg/engine/templating/resource_ref.go:48]: Do we need this or the merge line 33 is enough ?

Comment (bertbaron) [reply pkg/engine/templating/resource_ref.go:48]: That, or a change in the implementation of `GetLabels()`. Or maybe there is some other helper function or simpler way to implement this. The 'problem' with the current `GetLabels()` is that it will return no labels at all when there is at least one label with a non-string value.
